---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  is_file_root: true
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - test
  dependencies:
    - name: driver-one
      path: ./test/support
    - name: driver-two
      path: ./test/support

suites:
  - name: driver-one
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - driver-one
        driver-one.sls:
          hardware-profile:
            states:
              - name: driver-one
                hardware:
                  uuid: ce0ad9b1-f0ab-4f8b-a49f-f8e8082ecce6
                  manufacturer: Epson
                  model: TM-T88V
                  driverPath: s3://somebucket/drivers/Epson_JavaPOS_ADK_1141_for_Linux.tar.gz
                  type: printer
                  layer: Printer
                  jposEntry:
                    vendor:
                      name: DLA
                      url: http://www.adc.datalogic.com
                      factoryClass: com.dls.jpos.service.DLSScannerInstanceFactory
                      serviceClass: com.dls.jpos.service.DLSScannerService
                    jpos:
                      category: Scanner
                      version: "1.13"
                    properties:
                      8xxx:
                          key: 8xxx
                          type: String
                          value: True
                      deviceClass:
                          key: deviceClass
                          type: String
                          value: USBHHScanner
                      portName:
                          key: portName
                          type: String
                          value: 1
                      canAcceptStatisticsCmd:
                          key: canAcceptStatisticsCmd
                          type: String
                          value: "False"
                      canCompareFirmwareVersion:
                          key: canCompareFirmwareVersion
                          type: String
                          value: "False"
                      dataBits:
                          key: dataBits
                          type: String
                          value: 8
                      deviceName:
                          key: deviceName
                          type: String
                          value: "DLS Gryphon M4100 Scanner"
                      canNotifyPowerChange:
                          key: canNotifyPowerChange
                          type: String
                          value: False
                      canUpdateFirmware:
                          key: canUpdateFirmware
                          type: String
                          value: "False"
                      parity:
                          key: parity
                          type: String
                          value: None
                      flowControl:
                          key: flowControl
                          type: String
                          value: "Xon/Xoff"
                      stopBits:
                          key: stopBits
                          type: String
                          value: "1"
                      productId:
                          key: productId
                          type: String
                          value: 120b
                      deviceBus:
                          key: deviceBus
                          type: String
                          value: USB
                      vendorId:
                          key: vendorId
                          type: String
                          value: 05f9
                      usage:
                          key: usage
                          type: String
                          value: 4b00
                      deviceDescription:
                          key: deviceDescription
                          type: String
                          value: "DLS Gryphon M4100 Scanner"
                      baudRate:
                          key: baudRate
                          type: String
                          value: 9600
                  jposPath:
                    lib: /opt/EpsonJavaPOS:/opt/EpsonJavaPOS/lib:/opt/EpsonJavaPOS/bin:/var/epson_pcs/portcommunicationservice:/opt/EpsonJavaPOS/lib/epsonupos.H2000.jar:/opt/EpsonJavaPOS/lib/epsonupos.L90LinerFree.jar:/opt/EpsonJavaPOS/lib/pos.v4.0001_01.jar:/opt/EpsonJavaPOS/lib/epsonupos.admin.jar:/opt/EpsonJavaPOS/lib/epsonupos.m30.jar:/opt/EpsonJavaPOS/lib/epsonupos.T70II.jar:/opt/EpsonJavaPOS/lib/epsonupos.previous.jar:/opt/EpsonJavaPOS/lib/uposcommon.core.v1.14.0001.jar:/opt/EpsonJavaPOS/lib/epsonupos.T81II.jar:/opt/EpsonJavaPOS/lib/epsonupos.T82.jar:/opt/EpsonJavaPOS/lib/epsonupos.T88V.jar:/opt/EpsonJavaPOS/lib/epsonupos.T20.jar:/opt/EpsonJavaPOS/lib/pos.v4.0001_02.jar:/opt/EpsonJavaPOS/lib/epsonupos.P60II.jar:/opt/EpsonJavaPOS/lib/epsonupos.trace.jar:/opt/EpsonJavaPOS/lib/epsonupos.P20.jar:/opt/EpsonJavaPOS/lib/uposcommon.jar:/opt/EpsonJavaPOS/lib/uposcommon.core.v1.14.0001m.jar:/opt/EpsonJavaPOS/lib/pos.v4.0001.jar:/opt/EpsonJavaPOS/lib/epsonupos.T81.jar:/opt/EpsonJavaPOS/lib/epsonupos.Mobile1.jar:/opt/EpsonJavaPOS/lib/xercesImpl.jar:/opt/EpsonJavaPOS/lib/epsonupos.T82II.jar:/opt/EpsonJavaPOS/lib/epsonupos.core.v1.14.0001T1.jar:/opt/EpsonJavaPOS/lib/epsonupos.d30.jar:/opt/EpsonJavaPOS/lib/pos.jar:/opt/EpsonJavaPOS/lib/epsonupos.core.v1.14.0001m.jar:/opt/EpsonJavaPOS/lib/xml-apis.jar:/opt/EpsonJavaPOS/lib/epsonupos.core.v1.14.0001.jar:/opt/EpsonJavaPOS/lib/epsonupos.T20II.jar:/opt/EpsonJavaPOS/lib/epsonupos.jar:/opt/EpsonJavaPOS/lib/jpos1141.jar:/opt/EpsonJavaPOS/lib/epsonupos.P80.jar:/opt/EpsonJavaPOS/lib/epsonupos.T88VI.jar:/opt/EpsonJavaPOS/lib/epsonupos.L90.jar:/opt/EpsonJavaPOS/lib/epsonupos.H6000IV.jar
                    bin: /opt/EpsonJavaPOS:/opt/EpsonJavaPOS/lib:/opt/EpsonJavaPOS/bin:/var/epson_pcs/portcommunicationservice:/opt/epson_pcs/portcommunicationservice
              - name: driver-two
                hardware:
                  uuid: c97a4160-6169-43f1-9830-b7356b6a1f7e
                  manufacturer: Datalogic
                  model: GD4100-GD4400
                  driverPath: s3://somebucket/drivers/Datalogic_JavaPOS_113_SOMETHING_Linux.tar.gz
                  type: scanner
                  layer: Scanner
                  jposEntry:
                    vendor:
                      factoryClass: com.dls.jpos.service.DLSScannerInstanceFactory
                      serviceClass: com.dls.jpos.service.DLSScannerService
                      name: DLA
                      url: http://www.adc.datalogic.com
                    jpos:
                      category: Scanner
                      version: 1.13
                    properties:
                      8xxx:
                        key: 8xxx
                        type: String
                        value: True
                      deviceClass:
                        key: deviceClass
                        type: String
                        value: USBHHScanner
                      portName:
                        key: portName
                        type: String
                        value: 1
                      canAcceptStatisticsCmd:
                        key: canAcceptStatisticsCmd
                        type: String
                        value: "False"
                      canCompareFirmwareVersion:
                        key: canCompareFirmwareVersion
                        type: String
                        value: "False"
                      dataBits:
                        key: dataBits
                        type: String
                        value: 8
                      deviceName:
                        key: deviceName
                        type: String
                        value: "DLS Gryphon M4100 Scanner"
                      canNotifyPowerChange:
                        key: canNotifyPowerChange
                        type: String
                        value: False
                      canUpdateFirmware:
                        key: canUpdateFirmware
                        type: String
                        value: "False"
                      parity:
                        key: parity
                        type: String
                        value: None
                      flowControl:
                        key: flowControl
                        type: String
                        value: "Xon/Xoff"
                      stopBits:
                        key: stopBits
                        type: String
                        value: "1"
                      productId:
                        key: productId
                        type: String
                        value: 120b
                      deviceBus:
                        key: deviceBus
                        type: String
                        value: USB
                      vendorId:
                        key: vendorId
                        type: String
                        value: 05f9
                      usage:
                        key: usage
                        type: String
                        value: 4b00
                      deviceDescription:
                        key: deviceDescription
                        type: String
                        value: "DLS Gryphon M4100 Scanner"
                      baudRate:
                        key: baudRate
                        type: String
                        value: 9600
                    jposPath:
                      lib: /opt/dls/JavaPOS/DLSJavaPOS.jar:/opt/dls/JavaPOS/SupportJars/appframework-1.0.3.jar:/opt/dls/JavaPOS/SupportJars/beansbinding-1.2.1.jar:/opt/dls/JavaPOS/SupportJars/cmdfw.jar:/opt/dls/JavaPOS/SupportJars/comm.jar:/opt/dls/JavaPOS/SupportJars/jargs.jar:/opt/dls/JavaPOS/SupportJars/jcl.jar:/opt/dls/JavaPOS/SupportJars/jsr80.jar:/opt/dls/JavaPOS/SupportJars/jsr80_linux.jar:/opt/dls/JavaPOS/SupportJars/jsr80_ri.jar:/opt/dls/JavaPOS/SupportJars/jna-min-4.0.0.jar:/opt/dls/JavaPOS/SupportJars/jna-platform-4.0.0.jar:/opt/dls/JavaPOS/SupportJars/nrjavaserial-3.9.3.jar
                      bin: /opt/dls/JavaPOS:/opt/dls/JavaPOS/SupportJars
              - name: driver-three
                hardware:
                  uuid: ed454e71-ad5b-4cbe-94fa-27371f8a82ec
                  manufacturer: Diebold Nixdorf
                  model: BA63
                  driverPath: s3://somebucket/drivers/ProBase_JavaPOS_2-6_Linux.tar.gz
                  type: lineDisplay
                  layer: Linedisplay
                  jposEntry:
                    vendor: 
                      name: Diebold Nixdorf
                      url: http://www.dieboldnixdorf.com
                      factoryClass: com.wn.retail.jpos113.WNJposServiceInstanceFactoryIncLog
                      serviceClass: com.wn.retail.jpos113.WNLineDisplay
                      description: BA63 line display (2X20) at serial port (RS232)
                    jpos:
                      category: lineDisplay
                      version: 1.13
                    properties:
                      lines:
                        key: lines
                        type: String
                        value: 2
                      dcalClass:
                        key: dcalClass
                        type: String
                        value: "com.wn.retail.jpos113.dcal.SimpleCommDevice"
                      stopbits:
                        key: stopbits
                        type: String
                        value: 1
                      port:
                        key: port
                        type: String
                        value: "/dev/ttyS0"
                      protocol:
                        key: protocol
                        type: String
                        value: cts
                      parity:
                        key: parity
                        type: String
                        value: odd
                      dsrControl:
                        key: dsrControl
                        type: String
                        value: notused
                      baudrate:
                        key: baudrate
                        type: String
                        value: 9600
                      bits:
                        key: bits
                        type: String
                        value: 8
                      getDMIInfo:
                        key: getDMIInfo
                        type: String
                        value: on
                      infoConnectionType:
                        key: infoConnectionType
                        type: String
                        value: RS232
                      mapCharacterSetDefault:
                        key: mapCharacterSetDefault
                        type: String
                        value: false
                  jposPath:
                    lib: /opt/wn/javapos/lib/RXTXcomm.jar:/opt/wn/javapos/lib/TPGJavaPOS.jar:/opt/wn/javapos/lib/comm.jar:/opt/wn/javapos/lib/commons-logging.jar:/opt/wn/javapos/lib/jai_codec.jar:/opt/wn/javapos/lib/jai_core.jar:/opt/wn/javapos/lib/javapos-config-loader.jar:/opt/wn/javapos/lib/javapos-contracts.jar:/opt/wn/javapos/lib/jdd-base.jar:/opt/wn/javapos/lib/jdd-selv5.jar:/opt/wn/javapos/lib/jdd-usb.jar:/opt/wn/javapos/lib/jna-platform.jar:/opt/wn/javapos/lib/jna.jar:/opt/wn/javapos/lib/json-simple-1.1.1.jar:/opt/wn/javapos/lib/jsr80.jar:/opt/wn/javapos/lib/jsr80_linux.jar:/opt/wn/javapos/lib/jsr80_ri.jar:/opt/wn/javapos/lib/log4j/log4j-1.2.17.jar:/opt/wn/javapos/lib/mediator.jar:/opt/wn/javapos/lib/wn-cim.jar:/opt/wn/javapos/lib/wn-common-jnaio.jar:/opt/wn/javapos/lib/wn-common-rs232.jar:/opt/wn/javapos/lib/wn-common-usb.jar:/opt/wn/javapos/lib/wn-common.jar:/opt/wn/javapos/lib/wn-fwu-api.jar:/opt/wn/javapos/lib/wn-javapos-cashchanger.jar:/opt/wn/javapos/lib/wn-javapos-common.jar:/opt/wn/javapos/lib/wn-javapos-config.jar:/opt/wn/javapos/lib/wn-javapos-controls-src.jar:/opt/wn/javapos/lib/wn-javapos-controls.jar:/opt/wn/javapos/lib/wn-javapos-diagnostics.jar:/opt/wn/javapos/lib/wn-javapos-f53.jar:/opt/wn/javapos/lib/wn-javapos-fiscalprinter.jar:/opt/wn/javapos/lib/wn-javapos-iscan.jar:/opt/wn/javapos/lib/wn-javapos-jcl-editor.jar:/opt/wn/javapos/lib/wn-javapos-jcl.jar:/opt/wn/javapos/lib/wn-javapos-keylock.jar:/opt/wn/javapos/lib/wn-javapos-kkmps2.jar:/opt/wn/javapos/lib/wn-javapos-kkmusb.jar:/opt/wn/javapos/lib/wn-javapos-linedisplay.jar:/opt/wn/javapos/lib/wn-javapos-mps1086.jar:/opt/wn/javapos/lib/wn-javapos-msr.jar:/opt/wn/javapos/lib/wn-javapos-portalscanner.jar:/opt/wn/javapos/lib/wn-javapos-posprinter.jar:/opt/wn/javapos/lib/wn-javapos-ps7000.jar:/opt/wn/javapos/lib/wn-javapos-retail.jar:/opt/wn/javapos/lib/wn-javapos-samples.jar:/opt/wn/javapos/lib/wn-javapos-scanner.jar:/opt/wn/javapos/lib/wn-javapos-selaco.jar:/opt/wn/javapos/lib/wn-javapos-thxxx.jar:/opt/wn/javapos/lib/wn-javapos-tp07.jar:/opt/wn/javapos/lib/wn-javapos-trace.jar:/opt/wn/javapos/lib/wn-javapos-tsop.jar:/opt/wn/javapos/lib/wn-logger.jar:/opt/wn/javapos/lib/wn-udm-javapos.jar:/opt/wn/javapos/lib/xerces.jar
                    bin: /opt/wn/javapos
      state_top:
        base:
          '*':
              - up-driver-installer
